### ISSUE TITLE
Questions concerning commercial use and Unreal Engine 5.5

### ISSUE THREAD

**Issue by Hapybaka** [endink/Mediapipe4u-plugin#187]
### Feature Category

Others

### Feature Description

Hi Endink,
This is not a feature request, I just didn't know where to ask these questions, sorry. 

I was wondering two things. 

First, I noticed that there is a trial and a commercial version. 
I don't need the features of the commercial version and I was wondering if the trial version allowed commercial use. 
More specifically, I am considering using Unreal Engine for Vtubing, and I wanted to make sure that it wasn't infringing your license as the streams could be monetized. 
I would not distribute the application. 

My second question concerns the compatibility with Unreal Engine 5.5.
I would prefer to avoid downloading 5.4 because of the space it takes, so I wanted to ask if you think Mediapip4u would also work with 5.5.

Thank you for work, and take care!

**Comment by endink** [comment]
1.Use for any purpose is allowed, I have stopped providing commercial licenses because it is difficult for me alone to provide support for paid users, and the next version will be completely free.

2. UE5.5 is not supported at this moment, M4U will not be updated until January, a new version will be released in January, mainly to support more TTS and LLM (Ollama), I will try to support UE5.5 asap.


Google seems to have given up on updating the "pose" feature in Media Pipe, and I'm looking for a new solution for M4U.

**Comment by Hapybaka** [comment]
Hi Endlink, 
Thank you for the answer, this clarifies things. 

I heard that Google were changing MediaPipe.
In fact, I thought they already had left the project since some times, I was apprently wrong.

Thank you again for the project and the answers, it is very much appreciated.

Take care!
