### ISSUE TITLE
UE 5.1 Package Issue -- base64.cpp.obj ; error LNK2019

### ISSUE THREAD

**Issue by AOK-VISIONS** [endink/Mediapipe4u-plugin#52]
### MediaPipe4U Version

MediaPipe4U_ue_5_1_20230316

### UE Version

5.1.x

### UnrealEngine Type

Compiled From Source Code

### What happened?

I've been able to resolve all the issues I was having with packaging up to this point.
I am receiving this error code for base64.cpp.obj.
![Screenshot 2023-04-16 142226](https://user-images.githubusercontent.com/130712898/232333930-96c68d03-1377-4558-9960-458354a5d4b6.png)

I'd like to state this seems to be happening when trying to build from source code and/or from the launcher both ways.
![Screenshot 2023-04-16 142552](https://user-images.githubusercontent.com/130712898/232333936-0e199b0b-b596-401a-beb4-d23903ccf11f.png)
![Screenshot 2023-04-16 142614](https://user-images.githubusercontent.com/130712898/232333984-37edd10c-12e7-48a1-bddd-1033ae4d94b8.png)

I am using a clean demo project to make sure I could even package with your project, and I am having no luck.
Any help would be much appreciated. Thank you!

Here is a copy of the log as well in case it helps, but am willing to share more if needed to help resolve this.
![Screenshot 2023-04-16 143016](https://user-images.githubusercontent.com/130712898/232334119-172a5c4e-b9ff-499f-b83e-43d69c6e3c95.png)

**Comment by endink** [comment]
Your Windows SDK version? And VC version?

**Comment by AOK-VISIONS** [comment]
I am using Windows SDK 10.0.19041.0 on VS 2022.

**Comment by endink** [comment]
Try upgrade you windows sdk and VC++ SDK. 
Make sure:
- WINSDK: **10.0.22000** or later
- VC++: **14.35**   or later.

When UE starts to compile, you can see your WINDOWS SDK and VC version in the console.   
>Using Visual Studio 2022 [VC VERSION] toolchain (C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\[VC VERSION]) and Windows [Win SDK Version] SDK (C:\Program Files (x86)\Windows Kits\10).

Generally, you can just upgrade them to the latest version, because Microsoft always maintains backward compatibility.

**Comment by endink** [comment]
BTW：Once you upgrade the windows sdk, there will be requirements for the minimum OS version.   

For example, the Windows 11 SDK (10.0.22621.0) is compatible with the Windows 10 version 1507. Generally, this span is enough, because windows will also update automatically. So keep the environment up to date, this doesn't have much bad effect.

**Comment by AOK-VISIONS** [comment]
Of course the irony...  the license from that version ended the second I went to Build 🤣 BUT replaced it, and got it to package successfully and couldn't be happier. 

Problem solved!
Can't explain how many days I've been working with this.
I can't thank you enough!!! 😃

**Comment by endink** [comment]
Lol...

Glad to hear that you solved the problem, I will close this issue and improve the documentation.

Sorry again for wasting your time because the documentation is not perfect.

**Comment by AOK-VISIONS** [comment]
No thank you! 
It's a big learning experience for me. Appreciate it!
