### ISSUE TITLE
Arm sticking out and stretching

### ISSUE THREAD

**Issue by saechisaechi** [endink/Mediapipe4u-plugin#53]
### MediaPipe4U Version

M4U_5_0_20230409

### UE Version

5.0.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

Arm sticks out when not tracked, and stretches + distorts when i bring my left hand. 

https://user-images.githubusercontent.com/87157576/232376341-4bfadd75-bfa6-4b16-90df-bb3e1b8b1221.mp4

I've tried:
Wearing fitted shirts
better lighting
adjusting smoothing, min pose score thresh, twist correction enabled, and bone remapping
optomize
Use Leg IK
Use Arm IK

**Comment by endink** [comment]
I believe the problem is that you have incorrect bone mapping, and if it's mannequin, you don't need remap asset, just set the AnimationInstance property :
```
Presets = UE5
```

If you still want to use the remap asset that you created. MediaPipeRemapAsset can export as a json file through the "Export JSON" button in Remap Editor UI, you can paste the file content here, let's find the problem.

BTW: I recommend that you download the demo project, which is a fairly completed example with runtime UI, which is a good start to learning usages of this plugin.

**Comment by saechisaechi** [comment]
Okay, I tried with just mannequin and a custom model, and it worked just fine. Thank you!
